/**
 * Bamba API
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: desarrollo@vivebamba.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vivebamba.sdk.model;

import com.vivebamba.sdk.model.AdvisorUser;
import com.vivebamba.sdk.model.Message;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AdvisorMessageRequest {
  
  @SerializedName("customer")
  private AdvisorUser customer = null;
  @SerializedName("message")
  private Message message = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public AdvisorUser getCustomer() {
    return customer;
  }
  public void setCustomer(AdvisorUser customer) {
    this.customer = customer;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Message getMessage() {
    return message;
  }
  public void setMessage(Message message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdvisorMessageRequest advisorMessageRequest = (AdvisorMessageRequest) o;
    return (this.customer == null ? advisorMessageRequest.customer == null : this.customer.equals(advisorMessageRequest.customer)) &&
        (this.message == null ? advisorMessageRequest.message == null : this.message.equals(advisorMessageRequest.message));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.customer == null ? 0: this.customer.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdvisorMessageRequest {\n");
    
    sb.append("  customer: ").append(customer).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
