/**
 * Bamba API
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: desarrollo@vivebamba.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vivebamba.sdk.model;

import com.vivebamba.sdk.model.InlineResponse422Errors;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse422 {
  
  @SerializedName("errors")
  private List<InlineResponse422Errors> errors = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<InlineResponse422Errors> getErrors() {
    return errors;
  }
  public void setErrors(List<InlineResponse422Errors> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse422 inlineResponse422 = (InlineResponse422) o;
    return (this.errors == null ? inlineResponse422.errors == null : this.errors.equals(inlineResponse422.errors));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.errors == null ? 0: this.errors.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse422 {\n");
    
    sb.append("  errors: ").append(errors).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
