/**
 * Bamba API
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: desarrollo@vivebamba.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vivebamba.sdk.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Message {
  
  @SerializedName("from")
  private String from = null;
  @SerializedName("text")
  private String text = null;
  @SerializedName("sentAt")
  private Date sentAt = null;

  /**
   * The customer cellphone
   **/
  @ApiModelProperty(value = "The customer cellphone")
  public String getFrom() {
    return from;
  }
  public void setFrom(String from) {
    this.from = from;
  }

  /**
   * The text of the message
   **/
  @ApiModelProperty(value = "The text of the message")
  public String getText() {
    return text;
  }
  public void setText(String text) {
    this.text = text;
  }

  /**
   * The date and time (ISO 8601 format) when the message was sent
   **/
  @ApiModelProperty(value = "The date and time (ISO 8601 format) when the message was sent")
  public Date getSentAt() {
    return sentAt;
  }
  public void setSentAt(Date sentAt) {
    this.sentAt = sentAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return (this.from == null ? message.from == null : this.from.equals(message.from)) &&
        (this.text == null ? message.text == null : this.text.equals(message.text)) &&
        (this.sentAt == null ? message.sentAt == null : this.sentAt.equals(message.sentAt));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.from == null ? 0: this.from.hashCode());
    result = 31 * result + (this.text == null ? 0: this.text.hashCode());
    result = 31 * result + (this.sentAt == null ? 0: this.sentAt.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    
    sb.append("  from: ").append(from).append("\n");
    sb.append("  text: ").append(text).append("\n");
    sb.append("  sentAt: ").append(sentAt).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
