/**
 * Bamba API
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: desarrollo@vivebamba.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vivebamba.sdk.model;

import com.vivebamba.sdk.model.Customer;
import com.vivebamba.sdk.model.OrderProducts;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Order {
  
  @SerializedName("customer")
  private Customer customer = null;
  @SerializedName("products")
  private List<OrderProducts> products = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Customer getCustomer() {
    return customer;
  }
  public void setCustomer(Customer customer) {
    this.customer = customer;
  }

  /**
   * The collection of SKU from the products selected by the customer
   **/
  @ApiModelProperty(value = "The collection of SKU from the products selected by the customer")
  public List<OrderProducts> getProducts() {
    return products;
  }
  public void setProducts(List<OrderProducts> products) {
    this.products = products;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Order order = (Order) o;
    return (this.customer == null ? order.customer == null : this.customer.equals(order.customer)) &&
        (this.products == null ? order.products == null : this.products.equals(order.products));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.customer == null ? 0: this.customer.hashCode());
    result = 31 * result + (this.products == null ? 0: this.products.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Order {\n");
    
    sb.append("  customer: ").append(customer).append("\n");
    sb.append("  products: ").append(products).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
