/**
 * Bamba API
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: desarrollo@vivebamba.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vivebamba.sdk.model;

import com.vivebamba.sdk.model.ProductDescription;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Product {
  
  @SerializedName("sku")
  private String sku = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("price")
  private Double price = null;
  @SerializedName("image")
  private String image = null;
  @SerializedName("brief")
  private String brief = null;
  @SerializedName("description")
  private List<ProductDescription> description = null;
  @SerializedName("terms")
  private String terms = null;

  /**
   * A unique identifier for the product variant
   **/
  @ApiModelProperty(value = "A unique identifier for the product variant")
  public String getSku() {
    return sku;
  }
  public void setSku(String sku) {
    this.sku = sku;
  }

  /**
   * The name of the product
   **/
  @ApiModelProperty(value = "The name of the product")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * The price of the product
   **/
  @ApiModelProperty(value = "The price of the product")
  public Double getPrice() {
    return price;
  }
  public void setPrice(Double price) {
    this.price = price;
  }

  /**
   * Image of the product
   **/
  @ApiModelProperty(value = "Image of the product")
  public String getImage() {
    return image;
  }
  public void setImage(String image) {
    this.image = image;
  }

  /**
   * Plan benefit summary
   **/
  @ApiModelProperty(value = "Plan benefit summary")
  public String getBrief() {
    return brief;
  }
  public void setBrief(String brief) {
    this.brief = brief;
  }

  /**
   * Commercial information of the product by sections, the number of elements of each array is dynamic
   **/
  @ApiModelProperty(value = "Commercial information of the product by sections, the number of elements of each array is dynamic")
  public List<ProductDescription> getDescription() {
    return description;
  }
  public void setDescription(List<ProductDescription> description) {
    this.description = description;
  }

  /**
   * Link to terms and conditions detailed by product
   **/
  @ApiModelProperty(value = "Link to terms and conditions detailed by product")
  public String getTerms() {
    return terms;
  }
  public void setTerms(String terms) {
    this.terms = terms;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return (this.sku == null ? product.sku == null : this.sku.equals(product.sku)) &&
        (this.name == null ? product.name == null : this.name.equals(product.name)) &&
        (this.price == null ? product.price == null : this.price.equals(product.price)) &&
        (this.image == null ? product.image == null : this.image.equals(product.image)) &&
        (this.brief == null ? product.brief == null : this.brief.equals(product.brief)) &&
        (this.description == null ? product.description == null : this.description.equals(product.description)) &&
        (this.terms == null ? product.terms == null : this.terms.equals(product.terms));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sku == null ? 0: this.sku.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.image == null ? 0: this.image.hashCode());
    result = 31 * result + (this.brief == null ? 0: this.brief.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.terms == null ? 0: this.terms.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("  sku: ").append(sku).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  image: ").append(image).append("\n");
    sb.append("  brief: ").append(brief).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  terms: ").append(terms).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
