/**
 * Bamba API
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.2.6
 * Contact: desarrollo@vivebamba.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vivebamba.sdk.model;

import com.vivebamba.sdk.model.ProductBundleItems;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Product {
  
  @SerializedName("sku")
  private String sku = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("price")
  private Double price = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("image")
  private String image = null;
  @SerializedName("bundleItems")
  private List<ProductBundleItems> bundleItems = null;

  /**
   * A unique identifier for the product variant
   **/
  @ApiModelProperty(value = "A unique identifier for the product variant")
  public String getSku() {
    return sku;
  }
  public void setSku(String sku) {
    this.sku = sku;
  }

  /**
   * The name of the product
   **/
  @ApiModelProperty(value = "The name of the product")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * The price of the product
   **/
  @ApiModelProperty(value = "The price of the product")
  public Double getPrice() {
    return price;
  }
  public void setPrice(Double price) {
    this.price = price;
  }

  /**
   * Type of the product, it can be *bundle* or *not_bundle*
   **/
  @ApiModelProperty(value = "Type of the product, it can be *bundle* or *not_bundle*")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * Image of the product
   **/
  @ApiModelProperty(value = "Image of the product")
  public String getImage() {
    return image;
  }
  public void setImage(String image) {
    this.image = image;
  }

  /**
   * The collection of bundle items related to *bundle* products
   **/
  @ApiModelProperty(value = "The collection of bundle items related to *bundle* products")
  public List<ProductBundleItems> getBundleItems() {
    return bundleItems;
  }
  public void setBundleItems(List<ProductBundleItems> bundleItems) {
    this.bundleItems = bundleItems;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return (this.sku == null ? product.sku == null : this.sku.equals(product.sku)) &&
        (this.name == null ? product.name == null : this.name.equals(product.name)) &&
        (this.price == null ? product.price == null : this.price.equals(product.price)) &&
        (this.type == null ? product.type == null : this.type.equals(product.type)) &&
        (this.image == null ? product.image == null : this.image.equals(product.image)) &&
        (this.bundleItems == null ? product.bundleItems == null : this.bundleItems.equals(product.bundleItems));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sku == null ? 0: this.sku.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.image == null ? 0: this.image.hashCode());
    result = 31 * result + (this.bundleItems == null ? 0: this.bundleItems.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("  sku: ").append(sku).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  image: ").append(image).append("\n");
    sb.append("  bundleItems: ").append(bundleItems).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
