/**
 * Bamba API
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: desarrollo@vivebamba.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vivebamba.sdk.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductDetails {
  
  @SerializedName("head")
  private String head = null;
  @SerializedName("body")
  private List<String> body = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHead() {
    return head;
  }
  public void setHead(String head) {
    this.head = head;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getBody() {
    return body;
  }
  public void setBody(List<String> body) {
    this.body = body;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductDetails productDetails = (ProductDetails) o;
    return (this.head == null ? productDetails.head == null : this.head.equals(productDetails.head)) &&
        (this.body == null ? productDetails.body == null : this.body.equals(productDetails.body));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.head == null ? 0: this.head.hashCode());
    result = 31 * result + (this.body == null ? 0: this.body.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductDetails {\n");
    
    sb.append("  head: ").append(head).append("\n");
    sb.append("  body: ").append(body).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
