/**
 * Bamba API
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: desarrollo@vivebamba.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vivebamba.sdk.model;

import com.vivebamba.sdk.model.AnyOfobjectobject;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SectionWhatIncludes {
  
  @SerializedName("section")
  private String section = null;
  @SerializedName("details")
  private List<AnyOfobjectobject> details = null;

  /**
   * Section title
   **/
  @ApiModelProperty(value = "Section title")
  public String getSection() {
    return section;
  }
  public void setSection(String section) {
    this.section = section;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<AnyOfobjectobject> getDetails() {
    return details;
  }
  public void setDetails(List<AnyOfobjectobject> details) {
    this.details = details;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SectionWhatIncludes sectionWhatIncludes = (SectionWhatIncludes) o;
    return (this.section == null ? sectionWhatIncludes.section == null : this.section.equals(sectionWhatIncludes.section)) &&
        (this.details == null ? sectionWhatIncludes.details == null : this.details.equals(sectionWhatIncludes.details));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.section == null ? 0: this.section.hashCode());
    result = 31 * result + (this.details == null ? 0: this.details.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SectionWhatIncludes {\n");
    
    sb.append("  section: ").append(section).append("\n");
    sb.append("  details: ").append(details).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
