/**
 * Bamba API
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: desarrollo@vivebamba.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vivebamba.sdk.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Service {
  
  @SerializedName("policyNumber")
  private String policyNumber = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("state")
  private String state = null;
  @SerializedName("validFrom")
  private Date validFrom = null;
  @SerializedName("validTo")
  private Date validTo = null;

  /**
   * The policy number of the customer service, some services do not have it
   **/
  @ApiModelProperty(value = "The policy number of the customer service, some services do not have it")
  public String getPolicyNumber() {
    return policyNumber;
  }
  public void setPolicyNumber(String policyNumber) {
    this.policyNumber = policyNumber;
  }

  /**
   * The description of the service
   **/
  @ApiModelProperty(required = true, value = "The description of the service")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * The actual state of the service
   **/
  @ApiModelProperty(required = true, value = "The actual state of the service")
  public String getState() {
    return state;
  }
  public void setState(String state) {
    this.state = state;
  }

  /**
   * The date and time (ISO 8601 format) of start of validity of the service
   **/
  @ApiModelProperty(required = true, value = "The date and time (ISO 8601 format) of start of validity of the service")
  public Date getValidFrom() {
    return validFrom;
  }
  public void setValidFrom(Date validFrom) {
    this.validFrom = validFrom;
  }

  /**
   * The date and time (ISO 8601 format) of end of validity of the service
   **/
  @ApiModelProperty(required = true, value = "The date and time (ISO 8601 format) of end of validity of the service")
  public Date getValidTo() {
    return validTo;
  }
  public void setValidTo(Date validTo) {
    this.validTo = validTo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return (this.policyNumber == null ? service.policyNumber == null : this.policyNumber.equals(service.policyNumber)) &&
        (this.description == null ? service.description == null : this.description.equals(service.description)) &&
        (this.state == null ? service.state == null : this.state.equals(service.state)) &&
        (this.validFrom == null ? service.validFrom == null : this.validFrom.equals(service.validFrom)) &&
        (this.validTo == null ? service.validTo == null : this.validTo.equals(service.validTo));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.policyNumber == null ? 0: this.policyNumber.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    result = 31 * result + (this.validFrom == null ? 0: this.validFrom.hashCode());
    result = 31 * result + (this.validTo == null ? 0: this.validTo.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    
    sb.append("  policyNumber: ").append(policyNumber).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("  validFrom: ").append(validFrom).append("\n");
    sb.append("  validTo: ").append(validTo).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
