/**
 * Bamba API
 * SDK for Bamba API
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: desarrollo@vivebamba.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vivebamba.sdk.model;

import com.vivebamba.sdk.model.Service;
import java.util.*;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Subscription {
  
  @SerializedName("sku")
  private String sku = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("state")
  private String state = null;
  @SerializedName("validFrom")
  private Date validFrom = null;
  @SerializedName("validTo")
  private Date validTo = null;
  @SerializedName("relatedServices")
  private List<Service> relatedServices = null;

  /**
   * The SKU from product related to the subscription
   **/
  @ApiModelProperty(required = true, value = "The SKU from product related to the subscription")
  public String getSku() {
    return sku;
  }
  public void setSku(String sku) {
    this.sku = sku;
  }

  /**
   * The product name related to the subscription
   **/
  @ApiModelProperty(required = true, value = "The product name related to the subscription")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * The state of the subscription
   **/
  @ApiModelProperty(required = true, value = "The state of the subscription")
  public String getState() {
    return state;
  }
  public void setState(String state) {
    this.state = state;
  }

  /**
   * The date and time (ISO 8601 format) of start of validity of the subscription
   **/
  @ApiModelProperty(required = true, value = "The date and time (ISO 8601 format) of start of validity of the subscription")
  public Date getValidFrom() {
    return validFrom;
  }
  public void setValidFrom(Date validFrom) {
    this.validFrom = validFrom;
  }

  /**
   * The date and time (ISO 8601 format) of end of validity of the subscription
   **/
  @ApiModelProperty(required = true, value = "The date and time (ISO 8601 format) of end of validity of the subscription")
  public Date getValidTo() {
    return validTo;
  }
  public void setValidTo(Date validTo) {
    this.validTo = validTo;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Service> getRelatedServices() {
    return relatedServices;
  }
  public void setRelatedServices(List<Service> relatedServices) {
    this.relatedServices = relatedServices;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Subscription subscription = (Subscription) o;
    return (this.sku == null ? subscription.sku == null : this.sku.equals(subscription.sku)) &&
        (this.name == null ? subscription.name == null : this.name.equals(subscription.name)) &&
        (this.state == null ? subscription.state == null : this.state.equals(subscription.state)) &&
        (this.validFrom == null ? subscription.validFrom == null : this.validFrom.equals(subscription.validFrom)) &&
        (this.validTo == null ? subscription.validTo == null : this.validTo.equals(subscription.validTo)) &&
        (this.relatedServices == null ? subscription.relatedServices == null : this.relatedServices.equals(subscription.relatedServices));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sku == null ? 0: this.sku.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    result = 31 * result + (this.validFrom == null ? 0: this.validFrom.hashCode());
    result = 31 * result + (this.validTo == null ? 0: this.validTo.hashCode());
    result = 31 * result + (this.relatedServices == null ? 0: this.relatedServices.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Subscription {\n");
    
    sb.append("  sku: ").append(sku).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("  validFrom: ").append(validFrom).append("\n");
    sb.append("  validTo: ").append(validTo).append("\n");
    sb.append("  relatedServices: ").append(relatedServices).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
